version: "3"

services:
  db:
    image: mysql
    volumes: 
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_NAME
    ports:
      - 3306:3306
    restart: always

  api:
    build: .
    env_file: .env
    ports:
      - 8000:8000
    restart: always

volumes:
  data:
